# Project: diana_mola
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = diana_mola.o
LINKOBJ  = diana_mola.o
LIBS     = -L"C:/Users/usuario/Dev-Cpp/MinGW64/lib" -L"C:/Users/usuario/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/usuario/Dev-Cpp/MinGW64/include" -I"C:/Users/usuario/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/usuario/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/usuario/Dev-Cpp/MinGW64/include" -I"C:/Users/usuario/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/usuario/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/usuario/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = diana_mola.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

diana_mola.o: diana_mola.c
	$(CC) -c diana_mola.c -o diana_mola.o $(CFLAGS)
